/**
 * Every image key that existed in the hand-maintained sprite atlas
 * (`public/map/sprites/babs.json`) immediately before it was deleted in favour of
 * `@f-eld-ch/babs-sprites`.
 *
 * Retained as a fixture because it is the only remaining record of what a persisted
 * feature could legitimately be carrying. `legacyIconNames.test.ts` asserts that every
 * one of these still resolves, which is the guard against silently orphaning user data.
 *
 * Do not edit: this is history, not configuration.
 */

/** Non-pattern keys: candidates for `properties.icon`. */
export const LEGACY_ATLAS_ICON_KEYS = [
  "ABCDekontaminationsstelle",
  "AbsperrungVerkehrswege",
  "Angehoerigensammelstelle",
  "Atomunfall",
  "Autounfall",
  "BLaboratorium",
  "BeabsichtigteErkundung",
  "BeabsichtigteVerschiebung",
  "BeabsichtigterEinsatz",
  "Beobachtung",
  "Beschaedigung",
  "Betreuungsstelle",
  "Betriebsstoffabgabestelle",
  "Bezirksfuehrungsorgan",
  "Biounfall",
  "Bombenanschlag",
  "Bombendrohung",
  "Brand",
  "Brandanschlag",
  "BrandeinzelnesGebaeudeFlamme",
  "BranduebergriffErfolgt",
  "BranduebergriffGefahr",
  "Chemieunfall",
  "Chemikalien",
  "Debriefingstelle",
  "Demogewaltlos",
  "Demogewaltsam",
  "Drohung",
  "Duerre",
  "DurchgefuehrteErkundung",
  "DurchgefuehrteVerschiebung",
  "DurchgefuehrterEinsatz",
  "EingesperrteAbgeschnittene",
  "Einsatz",
  "Einsatzleiter",
  "Einsatzleitung",
  "Einsatzraum",
  "Einsatzzentrale",
  "Eisenbahnunglueck",
  "Energieausfall",
  "Epidemie",
  "Erdbeben",
  "Erdrutsch",
  "Explosion",
  "Fluechtlinge",
  "Flugzeugabsturz",
  "Gas",
  "Gebaeudeeinsturz",
  "GefahrElektrizitaet",
  "GefahrExplosion",
  "GefahrdurchLoeschenmitWasser",
  "GefahrentafelmitUNNummer",
  "GefahrfuerGrundwasser",
  "Gemeindefuehrungsorgan",
  "Gruppe",
  "Gruppenfuehrer",
  "Helikopterlandeplatz",
  "Informationsstelle",
  "Informationszentrum",
  "Infrastrukturschaden",
  "KGSNotdepot",
  "KGSNotlager",
  "KGSSammelpunkt",
  "Kadaversammelstelle",
  "Kanalisationsausfall",
  "KantonalesFuehrungsorgan",
  "KommandopostenFront",
  "KommandopostenRueckwaertiges",
  "Kommunikationsstoerung",
  "Kompanie",
  "Kontrollstelle",
  "Kontrollzentrum",
  "Lawine",
  "Massenpanik",
  "Materialdepot",
  "MobileEinsatzzentrale",
  "Obdachlose",
  "Oelverschmutzung",
  "OffizierZugfuehrer",
  "Patientensammelstelle",
  "Pforte",
  "Pluenderung",
  "RadioaktiveStoffe",
  "RegionalesFuehrungsorgan",
  "RettungsAchse",
  "Rutschgebiet",
  "Sabotage",
  "Sammelstelle",
  "Sanitaetshilfsstelle",
  "Sanitaetsumladestelle",
  "Schadengebiet",
  "Sperre",
  "StandortmobileFuehrungsstelle",
  "Starkniederschlag",
  "Stau",
  "Strerschwertbefahrbarbegehbar",
  "Streugutsammelstelle",
  "Strnichtbefahrbarschwerbegehbar",
  "Strunpassierbargesperrt",
  "Stuetzpunkt",
  "Sturm",
  "Tankloeschfahrzeug",
  "Teilzerstoerung",
  "Terroranschlag",
  "Tierseuche",
  "Totalzerstoerung",
  "Tote",
  "Totensammelstelle",
  "Trinkwasserabgabestelle",
  "TruemmerbereichSignatur",
  "Trupp",
  "UeberschwemmtesGebiet",
  "Ueberschwemmung",
  "Ueberwachung",
  "Umleitung",
  "Unfall",
  "Verkehrsposten",
  "Verletzte",
  "Verletztennest",
  "Vermisste",
  "Verpflegungsabgabestelle",
  "Verschiebung",
  "Wasservsgausfall",
  "Wasserwerfer",
  "ZivilesFuehrungsorgan",
  "Zug",
] as const;

/** Pattern tile keys: referenced by zoneType/lineType, never stored as an icon. */
export const LEGACY_ATLAS_PATTERN_KEYS = [
  "PatternBeabsichtigteErkundung",
  "PatternBrandzone",
  "PatternLineBeabsichtigteErkundung",
  "PatternLineErkundung",
  "PatternLineRettungsachse",
  "PatternLineRutschgebiet",
  "PatternLineRutschgebietGespiegelt",
  "PatternLineUnpassierbar",
  "PatternZerstoert",
] as const;
