name: sitrep
services:
  sitrep:
    depends_on:
      postgres:
        condition: service_started
    environment:
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres?sslmode=disable
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
      OIDC_ISSUER: https://${SITREP_HOSTNAME}/dex
      OIDC_REDIRECT_URL: https://${SITREP_HOSTNAME}/oauth2/callback
      COOKIE_KEY: ${COOKIE_KEY}
      SERVER_PORT: 4180
    image: ghcr.io/f-eld-ch/sitrep:edge
    extra_hosts:
      - "${SITREP_HOSTNAME}:host-gateway"
    networks:
      default: null
    ports:
      - mode: ingress
        target: 4180
        published: "4180"
        protocol: tcp
    restart: always
  postgres:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    image: postgis/postgis:14-3.2
    networks:
      default: null
    restart: always
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/postgresql/data
        volume: {}
    ports:
      - mode: ingress
        target: 5432
        published: "5432"
        protocol: tcp
  dex:
    image: docker.io/dexidp/dex:v2.38.0
    environment:
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
      DEX_CONNECTORS_ENABLE_MOCK: "true"
      DEX_CONNECTORS_ENABLE_DEMO_USER: "true"
      DEX_ISSUER: https://${SITREP_HOSTNAME}/dex
      OIDC_REDIRECT_URL: https://${SITREP_HOSTNAME}/oauth2/callback
    networks:
      default: null
    restart: always
    extra_hosts:
      - "${SITREP_HOSTNAME}:host-gateway"
    command: dex serve /etc/dex/config-demo.yaml
    volumes:
      - type: bind
        source: ./dexidp/config-demo.yaml
        target: /etc/dex/config-demo.yaml
        read_only: true
      - type: volume
        source: dex_data
        target: /var/sqlite/dex
        volume: {}
    ports:
      - mode: ingress
        target: 5556
        published: "5556"
        protocol: tcp
      - mode: ingress
        target: 5557
        published: "5557"
        protocol: tcp
networks:
  default:
    name: sitrep_default
volumes:
  db_data:
    name: sitrep_db_data
  dex_data:
    name: sitrep_dex_data
