/* eslint-disable */
import * as types from './graphql';
import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  query FetchIncidents {\n    incidents {\n      id\n      name\n      createdAt\n      updatedAt\n      closedAt\n      isClosed\n      location {\n        name\n        coordinates\n      }\n    }\n  }\n": typeof types.FetchIncidentsDocument,
    "\n  query GetIncidentDetail($incidentId: ID!) {\n    incident(id: $incidentId) {\n      id\n      name\n      createdAt\n      updatedAt\n      closedAt\n      isClosed\n      location {\n        name\n        coordinates\n      }\n      divisions {\n        id\n        name\n        description\n      }\n    }\n  }\n": typeof types.GetIncidentDetailDocument,
    "\n  mutation CreateIncident(\n    $name: String!\n    $location: String\n    $divisions: [DivisionInput!]!\n    $layers: [LayerInput!]!\n  ) {\n    createIncident(\n      input: { name: $name, location: $location, divisions: $divisions, layers: $layers }\n    ) {\n      id\n      name\n      divisions {\n        id\n        name\n        description\n      }\n    }\n  }\n": typeof types.CreateIncidentDocument,
    "\n  mutation UpdateIncident($id: ID!, $name: String, $location: String, $divisions: [DivisionInput!]) {\n    updateIncident(id: $id, input: { name: $name, location: $location, divisions: $divisions }) {\n      id\n      name\n      location {\n        name\n        coordinates\n      }\n      divisions {\n        id\n        name\n        description\n      }\n    }\n  }\n": typeof types.UpdateIncidentDocument,
    "\n  mutation CloseIncident($id: ID!) {\n    closeIncident(id: $id) {\n      id\n      closedAt\n      isClosed\n    }\n  }\n": typeof types.CloseIncidentDocument,
    "\n  mutation ReopenIncident($id: ID!) {\n    reopenIncident(id: $id) {\n      id\n      closedAt\n      isClosed\n    }\n  }\n": typeof types.ReopenIncidentDocument,
    "\n  mutation DeleteIncident($id: ID!) {\n    deleteIncident(id: $id)\n  }\n": typeof types.DeleteIncidentDocument,
    "\n  query GetLayersForIncident($incidentId: ID!) {\n    layersForIncident(incidentId: $incidentId) {\n      id\n      name\n      revision\n      features {\n        id\n        geometry\n        properties\n      }\n    }\n  }\n": typeof types.GetLayersForIncidentDocument,
    "\n  mutation AddFeature(\n    $incidentId: ID!\n    $layerId: ID!\n    $id: ID!\n    $geometry: Geometry\n    $properties: JSONObject\n  ) {\n    addFeature(\n      incidentId: $incidentId\n      layerId: $layerId\n      id: $id\n      geometry: $geometry\n      properties: $properties\n    ) {\n      id\n      geometry\n      properties\n    }\n  }\n": typeof types.AddFeatureDocument,
    "\n  mutation ModifyFeature($id: ID!, $geometry: Geometry, $properties: JSONObject) {\n    modifyFeature(id: $id, geometry: $geometry, properties: $properties) {\n      id\n      geometry\n      properties\n    }\n  }\n": typeof types.ModifyFeatureDocument,
    "\n  mutation DeleteFeature($id: ID!) {\n    deleteFeature(id: $id)\n  }\n": typeof types.DeleteFeatureDocument,
    "\n  mutation CreateLayer($incidentId: ID!, $name: String!) {\n    createLayer(incidentId: $incidentId, name: $name) {\n      id\n      name\n    }\n  }\n": typeof types.CreateLayerDocument,
    "\n  query GetIncidentMessages($incidentId: ID!) {\n    incident(id: $incidentId) {\n      id\n      divisions {\n        id\n        name\n        description\n      }\n      messages {\n        id\n        number\n        sender\n        receiver\n        senderDetail\n        receiverDetail\n        content\n        medium\n        time\n        createdAt\n        updatedAt\n        triage\n        priority\n        divisions {\n          id\n          name\n          description\n        }\n      }\n    }\n  }\n": typeof types.GetIncidentMessagesDocument,
    "\n  query GetMessageForTriage($messageId: ID!, $incidentId: ID!) {\n    message(id: $messageId) {\n      id\n      number\n      sender\n      receiver\n      senderDetail\n      receiverDetail\n      content\n      medium\n      time\n      createdAt\n      updatedAt\n      triage\n      priority\n      divisions {\n        id\n        name\n        description\n      }\n    }\n    incident(id: $incidentId) {\n      divisions {\n        id\n        name\n        description\n      }\n    }\n  }\n": typeof types.GetMessageForTriageDocument,
    "\n  mutation CreateMessage(\n    $incidentId: ID!\n    $sender: String!\n    $receiver: String!\n    $senderDetail: String!\n    $receiverDetail: String!\n    $content: String!\n    $medium: Medium!\n    $time: DateTime\n  ) {\n    createMessage(\n      input: {\n        incidentId: $incidentId\n        sender: $sender\n        receiver: $receiver\n        senderDetail: $senderDetail\n        receiverDetail: $receiverDetail\n        content: $content\n        medium: $medium\n        time: $time\n      }\n    ) {\n      id\n      number\n      sender\n      receiver\n      senderDetail\n      receiverDetail\n      content\n      medium\n      time\n      createdAt\n      updatedAt\n      triage\n      priority\n      divisions {\n        id\n        name\n        description\n      }\n    }\n  }\n": typeof types.CreateMessageDocument,
    "\n  mutation UpdateMessage(\n    $id: ID!\n    $sender: String\n    $receiver: String\n    $senderDetail: String\n    $receiverDetail: String\n    $content: String\n    $medium: Medium\n    $time: DateTime\n  ) {\n    updateMessage(\n      id: $id\n      input: {\n        sender: $sender\n        receiver: $receiver\n        senderDetail: $senderDetail\n        receiverDetail: $receiverDetail\n        content: $content\n        medium: $medium\n        time: $time\n      }\n    ) {\n      id\n      number\n      sender\n      receiver\n      senderDetail\n      receiverDetail\n      content\n      medium\n      time\n      createdAt\n      updatedAt\n      triage\n      priority\n      divisions {\n        id\n        name\n        description\n      }\n    }\n  }\n": typeof types.UpdateMessageDocument,
    "\n  mutation TriageMessage(\n    $id: ID!\n    $triage: TriageStatus!\n    $priority: PriorityStatus!\n    $divisionIds: [ID!]!\n  ) {\n    triageMessage(\n      id: $id\n      input: { triage: $triage, priority: $priority, divisionIds: $divisionIds }\n    ) {\n      id\n      triage\n      priority\n      divisions {\n        id\n        name\n        description\n      }\n    }\n  }\n": typeof types.TriageMessageDocument,
};
const documents: Documents = {
    "\n  query FetchIncidents {\n    incidents {\n      id\n      name\n      createdAt\n      updatedAt\n      closedAt\n      isClosed\n      location {\n        name\n        coordinates\n      }\n    }\n  }\n": types.FetchIncidentsDocument,
    "\n  query GetIncidentDetail($incidentId: ID!) {\n    incident(id: $incidentId) {\n      id\n      name\n      createdAt\n      updatedAt\n      closedAt\n      isClosed\n      location {\n        name\n        coordinates\n      }\n      divisions {\n        id\n        name\n        description\n      }\n    }\n  }\n": types.GetIncidentDetailDocument,
    "\n  mutation CreateIncident(\n    $name: String!\n    $location: String\n    $divisions: [DivisionInput!]!\n    $layers: [LayerInput!]!\n  ) {\n    createIncident(\n      input: { name: $name, location: $location, divisions: $divisions, layers: $layers }\n    ) {\n      id\n      name\n      divisions {\n        id\n        name\n        description\n      }\n    }\n  }\n": types.CreateIncidentDocument,
    "\n  mutation UpdateIncident($id: ID!, $name: String, $location: String, $divisions: [DivisionInput!]) {\n    updateIncident(id: $id, input: { name: $name, location: $location, divisions: $divisions }) {\n      id\n      name\n      location {\n        name\n        coordinates\n      }\n      divisions {\n        id\n        name\n        description\n      }\n    }\n  }\n": types.UpdateIncidentDocument,
    "\n  mutation CloseIncident($id: ID!) {\n    closeIncident(id: $id) {\n      id\n      closedAt\n      isClosed\n    }\n  }\n": types.CloseIncidentDocument,
    "\n  mutation ReopenIncident($id: ID!) {\n    reopenIncident(id: $id) {\n      id\n      closedAt\n      isClosed\n    }\n  }\n": types.ReopenIncidentDocument,
    "\n  mutation DeleteIncident($id: ID!) {\n    deleteIncident(id: $id)\n  }\n": types.DeleteIncidentDocument,
    "\n  query GetLayersForIncident($incidentId: ID!) {\n    layersForIncident(incidentId: $incidentId) {\n      id\n      name\n      revision\n      features {\n        id\n        geometry\n        properties\n      }\n    }\n  }\n": types.GetLayersForIncidentDocument,
    "\n  mutation AddFeature(\n    $incidentId: ID!\n    $layerId: ID!\n    $id: ID!\n    $geometry: Geometry\n    $properties: JSONObject\n  ) {\n    addFeature(\n      incidentId: $incidentId\n      layerId: $layerId\n      id: $id\n      geometry: $geometry\n      properties: $properties\n    ) {\n      id\n      geometry\n      properties\n    }\n  }\n": types.AddFeatureDocument,
    "\n  mutation ModifyFeature($id: ID!, $geometry: Geometry, $properties: JSONObject) {\n    modifyFeature(id: $id, geometry: $geometry, properties: $properties) {\n      id\n      geometry\n      properties\n    }\n  }\n": types.ModifyFeatureDocument,
    "\n  mutation DeleteFeature($id: ID!) {\n    deleteFeature(id: $id)\n  }\n": types.DeleteFeatureDocument,
    "\n  mutation CreateLayer($incidentId: ID!, $name: String!) {\n    createLayer(incidentId: $incidentId, name: $name) {\n      id\n      name\n    }\n  }\n": types.CreateLayerDocument,
    "\n  query GetIncidentMessages($incidentId: ID!) {\n    incident(id: $incidentId) {\n      id\n      divisions {\n        id\n        name\n        description\n      }\n      messages {\n        id\n        number\n        sender\n        receiver\n        senderDetail\n        receiverDetail\n        content\n        medium\n        time\n        createdAt\n        updatedAt\n        triage\n        priority\n        divisions {\n          id\n          name\n          description\n        }\n      }\n    }\n  }\n": types.GetIncidentMessagesDocument,
    "\n  query GetMessageForTriage($messageId: ID!, $incidentId: ID!) {\n    message(id: $messageId) {\n      id\n      number\n      sender\n      receiver\n      senderDetail\n      receiverDetail\n      content\n      medium\n      time\n      createdAt\n      updatedAt\n      triage\n      priority\n      divisions {\n        id\n        name\n        description\n      }\n    }\n    incident(id: $incidentId) {\n      divisions {\n        id\n        name\n        description\n      }\n    }\n  }\n": types.GetMessageForTriageDocument,
    "\n  mutation CreateMessage(\n    $incidentId: ID!\n    $sender: String!\n    $receiver: String!\n    $senderDetail: String!\n    $receiverDetail: String!\n    $content: String!\n    $medium: Medium!\n    $time: DateTime\n  ) {\n    createMessage(\n      input: {\n        incidentId: $incidentId\n        sender: $sender\n        receiver: $receiver\n        senderDetail: $senderDetail\n        receiverDetail: $receiverDetail\n        content: $content\n        medium: $medium\n        time: $time\n      }\n    ) {\n      id\n      number\n      sender\n      receiver\n      senderDetail\n      receiverDetail\n      content\n      medium\n      time\n      createdAt\n      updatedAt\n      triage\n      priority\n      divisions {\n        id\n        name\n        description\n      }\n    }\n  }\n": types.CreateMessageDocument,
    "\n  mutation UpdateMessage(\n    $id: ID!\n    $sender: String\n    $receiver: String\n    $senderDetail: String\n    $receiverDetail: String\n    $content: String\n    $medium: Medium\n    $time: DateTime\n  ) {\n    updateMessage(\n      id: $id\n      input: {\n        sender: $sender\n        receiver: $receiver\n        senderDetail: $senderDetail\n        receiverDetail: $receiverDetail\n        content: $content\n        medium: $medium\n        time: $time\n      }\n    ) {\n      id\n      number\n      sender\n      receiver\n      senderDetail\n      receiverDetail\n      content\n      medium\n      time\n      createdAt\n      updatedAt\n      triage\n      priority\n      divisions {\n        id\n        name\n        description\n      }\n    }\n  }\n": types.UpdateMessageDocument,
    "\n  mutation TriageMessage(\n    $id: ID!\n    $triage: TriageStatus!\n    $priority: PriorityStatus!\n    $divisionIds: [ID!]!\n  ) {\n    triageMessage(\n      id: $id\n      input: { triage: $triage, priority: $priority, divisionIds: $divisionIds }\n    ) {\n      id\n      triage\n      priority\n      divisions {\n        id\n        name\n        description\n      }\n    }\n  }\n": types.TriageMessageDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query FetchIncidents {\n    incidents {\n      id\n      name\n      createdAt\n      updatedAt\n      closedAt\n      isClosed\n      location {\n        name\n        coordinates\n      }\n    }\n  }\n"): (typeof documents)["\n  query FetchIncidents {\n    incidents {\n      id\n      name\n      createdAt\n      updatedAt\n      closedAt\n      isClosed\n      location {\n        name\n        coordinates\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetIncidentDetail($incidentId: ID!) {\n    incident(id: $incidentId) {\n      id\n      name\n      createdAt\n      updatedAt\n      closedAt\n      isClosed\n      location {\n        name\n        coordinates\n      }\n      divisions {\n        id\n        name\n        description\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetIncidentDetail($incidentId: ID!) {\n    incident(id: $incidentId) {\n      id\n      name\n      createdAt\n      updatedAt\n      closedAt\n      isClosed\n      location {\n        name\n        coordinates\n      }\n      divisions {\n        id\n        name\n        description\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateIncident(\n    $name: String!\n    $location: String\n    $divisions: [DivisionInput!]!\n    $layers: [LayerInput!]!\n  ) {\n    createIncident(\n      input: { name: $name, location: $location, divisions: $divisions, layers: $layers }\n    ) {\n      id\n      name\n      divisions {\n        id\n        name\n        description\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation CreateIncident(\n    $name: String!\n    $location: String\n    $divisions: [DivisionInput!]!\n    $layers: [LayerInput!]!\n  ) {\n    createIncident(\n      input: { name: $name, location: $location, divisions: $divisions, layers: $layers }\n    ) {\n      id\n      name\n      divisions {\n        id\n        name\n        description\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation UpdateIncident($id: ID!, $name: String, $location: String, $divisions: [DivisionInput!]) {\n    updateIncident(id: $id, input: { name: $name, location: $location, divisions: $divisions }) {\n      id\n      name\n      location {\n        name\n        coordinates\n      }\n      divisions {\n        id\n        name\n        description\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateIncident($id: ID!, $name: String, $location: String, $divisions: [DivisionInput!]) {\n    updateIncident(id: $id, input: { name: $name, location: $location, divisions: $divisions }) {\n      id\n      name\n      location {\n        name\n        coordinates\n      }\n      divisions {\n        id\n        name\n        description\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CloseIncident($id: ID!) {\n    closeIncident(id: $id) {\n      id\n      closedAt\n      isClosed\n    }\n  }\n"): (typeof documents)["\n  mutation CloseIncident($id: ID!) {\n    closeIncident(id: $id) {\n      id\n      closedAt\n      isClosed\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation ReopenIncident($id: ID!) {\n    reopenIncident(id: $id) {\n      id\n      closedAt\n      isClosed\n    }\n  }\n"): (typeof documents)["\n  mutation ReopenIncident($id: ID!) {\n    reopenIncident(id: $id) {\n      id\n      closedAt\n      isClosed\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation DeleteIncident($id: ID!) {\n    deleteIncident(id: $id)\n  }\n"): (typeof documents)["\n  mutation DeleteIncident($id: ID!) {\n    deleteIncident(id: $id)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetLayersForIncident($incidentId: ID!) {\n    layersForIncident(incidentId: $incidentId) {\n      id\n      name\n      revision\n      features {\n        id\n        geometry\n        properties\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetLayersForIncident($incidentId: ID!) {\n    layersForIncident(incidentId: $incidentId) {\n      id\n      name\n      revision\n      features {\n        id\n        geometry\n        properties\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation AddFeature(\n    $incidentId: ID!\n    $layerId: ID!\n    $id: ID!\n    $geometry: Geometry\n    $properties: JSONObject\n  ) {\n    addFeature(\n      incidentId: $incidentId\n      layerId: $layerId\n      id: $id\n      geometry: $geometry\n      properties: $properties\n    ) {\n      id\n      geometry\n      properties\n    }\n  }\n"): (typeof documents)["\n  mutation AddFeature(\n    $incidentId: ID!\n    $layerId: ID!\n    $id: ID!\n    $geometry: Geometry\n    $properties: JSONObject\n  ) {\n    addFeature(\n      incidentId: $incidentId\n      layerId: $layerId\n      id: $id\n      geometry: $geometry\n      properties: $properties\n    ) {\n      id\n      geometry\n      properties\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation ModifyFeature($id: ID!, $geometry: Geometry, $properties: JSONObject) {\n    modifyFeature(id: $id, geometry: $geometry, properties: $properties) {\n      id\n      geometry\n      properties\n    }\n  }\n"): (typeof documents)["\n  mutation ModifyFeature($id: ID!, $geometry: Geometry, $properties: JSONObject) {\n    modifyFeature(id: $id, geometry: $geometry, properties: $properties) {\n      id\n      geometry\n      properties\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation DeleteFeature($id: ID!) {\n    deleteFeature(id: $id)\n  }\n"): (typeof documents)["\n  mutation DeleteFeature($id: ID!) {\n    deleteFeature(id: $id)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateLayer($incidentId: ID!, $name: String!) {\n    createLayer(incidentId: $incidentId, name: $name) {\n      id\n      name\n    }\n  }\n"): (typeof documents)["\n  mutation CreateLayer($incidentId: ID!, $name: String!) {\n    createLayer(incidentId: $incidentId, name: $name) {\n      id\n      name\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetIncidentMessages($incidentId: ID!) {\n    incident(id: $incidentId) {\n      id\n      divisions {\n        id\n        name\n        description\n      }\n      messages {\n        id\n        number\n        sender\n        receiver\n        senderDetail\n        receiverDetail\n        content\n        medium\n        time\n        createdAt\n        updatedAt\n        triage\n        priority\n        divisions {\n          id\n          name\n          description\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetIncidentMessages($incidentId: ID!) {\n    incident(id: $incidentId) {\n      id\n      divisions {\n        id\n        name\n        description\n      }\n      messages {\n        id\n        number\n        sender\n        receiver\n        senderDetail\n        receiverDetail\n        content\n        medium\n        time\n        createdAt\n        updatedAt\n        triage\n        priority\n        divisions {\n          id\n          name\n          description\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetMessageForTriage($messageId: ID!, $incidentId: ID!) {\n    message(id: $messageId) {\n      id\n      number\n      sender\n      receiver\n      senderDetail\n      receiverDetail\n      content\n      medium\n      time\n      createdAt\n      updatedAt\n      triage\n      priority\n      divisions {\n        id\n        name\n        description\n      }\n    }\n    incident(id: $incidentId) {\n      divisions {\n        id\n        name\n        description\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetMessageForTriage($messageId: ID!, $incidentId: ID!) {\n    message(id: $messageId) {\n      id\n      number\n      sender\n      receiver\n      senderDetail\n      receiverDetail\n      content\n      medium\n      time\n      createdAt\n      updatedAt\n      triage\n      priority\n      divisions {\n        id\n        name\n        description\n      }\n    }\n    incident(id: $incidentId) {\n      divisions {\n        id\n        name\n        description\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateMessage(\n    $incidentId: ID!\n    $sender: String!\n    $receiver: String!\n    $senderDetail: String!\n    $receiverDetail: String!\n    $content: String!\n    $medium: Medium!\n    $time: DateTime\n  ) {\n    createMessage(\n      input: {\n        incidentId: $incidentId\n        sender: $sender\n        receiver: $receiver\n        senderDetail: $senderDetail\n        receiverDetail: $receiverDetail\n        content: $content\n        medium: $medium\n        time: $time\n      }\n    ) {\n      id\n      number\n      sender\n      receiver\n      senderDetail\n      receiverDetail\n      content\n      medium\n      time\n      createdAt\n      updatedAt\n      triage\n      priority\n      divisions {\n        id\n        name\n        description\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation CreateMessage(\n    $incidentId: ID!\n    $sender: String!\n    $receiver: String!\n    $senderDetail: String!\n    $receiverDetail: String!\n    $content: String!\n    $medium: Medium!\n    $time: DateTime\n  ) {\n    createMessage(\n      input: {\n        incidentId: $incidentId\n        sender: $sender\n        receiver: $receiver\n        senderDetail: $senderDetail\n        receiverDetail: $receiverDetail\n        content: $content\n        medium: $medium\n        time: $time\n      }\n    ) {\n      id\n      number\n      sender\n      receiver\n      senderDetail\n      receiverDetail\n      content\n      medium\n      time\n      createdAt\n      updatedAt\n      triage\n      priority\n      divisions {\n        id\n        name\n        description\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation UpdateMessage(\n    $id: ID!\n    $sender: String\n    $receiver: String\n    $senderDetail: String\n    $receiverDetail: String\n    $content: String\n    $medium: Medium\n    $time: DateTime\n  ) {\n    updateMessage(\n      id: $id\n      input: {\n        sender: $sender\n        receiver: $receiver\n        senderDetail: $senderDetail\n        receiverDetail: $receiverDetail\n        content: $content\n        medium: $medium\n        time: $time\n      }\n    ) {\n      id\n      number\n      sender\n      receiver\n      senderDetail\n      receiverDetail\n      content\n      medium\n      time\n      createdAt\n      updatedAt\n      triage\n      priority\n      divisions {\n        id\n        name\n        description\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateMessage(\n    $id: ID!\n    $sender: String\n    $receiver: String\n    $senderDetail: String\n    $receiverDetail: String\n    $content: String\n    $medium: Medium\n    $time: DateTime\n  ) {\n    updateMessage(\n      id: $id\n      input: {\n        sender: $sender\n        receiver: $receiver\n        senderDetail: $senderDetail\n        receiverDetail: $receiverDetail\n        content: $content\n        medium: $medium\n        time: $time\n      }\n    ) {\n      id\n      number\n      sender\n      receiver\n      senderDetail\n      receiverDetail\n      content\n      medium\n      time\n      createdAt\n      updatedAt\n      triage\n      priority\n      divisions {\n        id\n        name\n        description\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation TriageMessage(\n    $id: ID!\n    $triage: TriageStatus!\n    $priority: PriorityStatus!\n    $divisionIds: [ID!]!\n  ) {\n    triageMessage(\n      id: $id\n      input: { triage: $triage, priority: $priority, divisionIds: $divisionIds }\n    ) {\n      id\n      triage\n      priority\n      divisions {\n        id\n        name\n        description\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation TriageMessage(\n    $id: ID!\n    $triage: TriageStatus!\n    $priority: PriorityStatus!\n    $divisionIds: [ID!]!\n  ) {\n    triageMessage(\n      id: $id\n      input: { triage: $triage, priority: $priority, divisionIds: $divisionIds }\n    ) {\n      id\n      triage\n      priority\n      divisions {\n        id\n        name\n        description\n      }\n    }\n  }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;