FROM docker.io/hasura/graphql-engine:v2.45.2-ce.cli-migrations-v3.ubi
COPY hasura/migrations /hasura-migrations
COPY hasura/metadata /hasura-metadata
ENV HASURA_GRAPHQL_EXPERIMENTAL_FEATURES=naming_convention
ENV HASURA_GRAPHQL_DEFAULT_NAMING_CONVENTION=graphql-default
ENV HASURA_GRAPHQL_ENABLE_TELEMETRY=false
