package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/f-eld-ch/sitrep/graph/model"
)

// ID is the resolver for the id field.
func (r *divisionResolver) ID(ctx context.Context, obj *model.Division) (string, error) {
	return obj.ID.String(), nil
}

// Division returns DivisionResolver implementation.
func (r *Resolver) Division() DivisionResolver { return &divisionResolver{r} }

type divisionResolver struct{ *Resolver }
