// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/f-eld-ch/sitrep/internal/adapter/inbound/graphql/scalar"
)

type CreateIncidentInput struct {
	Name string `json:"name"`
	// Location display name; server creates the Location record.
	Location  *string          `json:"location,omitempty"`
	Divisions []*DivisionInput `json:"divisions"`
	// Map layers to create alongside the incident. Empty → one default layer.
	Layers []*LayerInput `json:"layers"`
}

type CreateMessageInput struct {
	IncidentID     string `json:"incidentId"`
	Sender         string `json:"sender"`
	Receiver       string `json:"receiver"`
	SenderDetail   string `json:"senderDetail"`
	ReceiverDetail string `json:"receiverDetail"`
	Content        string `json:"content"`
	Medium         Medium `json:"medium"`
	// Defaults to the server's current time when omitted.
	Time *time.Time `json:"time,omitempty"`
}

type Division struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type DivisionInput struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Feature struct {
	ID         string         `json:"id"`
	Geometry   scalar.JSONMap `json:"geometry,omitempty"`
	Properties scalar.JSONMap `json:"properties,omitempty"`
}

type Incident struct {
	ID        string      `json:"id"`
	Name      string      `json:"name"`
	CreatedAt time.Time   `json:"createdAt"`
	UpdatedAt time.Time   `json:"updatedAt"`
	ClosedAt  *time.Time  `json:"closedAt,omitempty"`
	IsClosed  bool        `json:"isClosed"`
	Location  *Location   `json:"location,omitempty"`
	Divisions []*Division `json:"divisions"`
	// All messages for this incident, newest first.
	Messages []*Message `json:"messages"`
}

type Layer struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	// Revision counter; increments on every feature change. Use for change detection.
	Revision int        `json:"revision"`
	Features []*Feature `json:"features"`
}

type LayerInput struct {
	Name string `json:"name"`
}

type Location struct {
	Name        string         `json:"name"`
	Coordinates scalar.JSONMap `json:"coordinates,omitempty"`
}

type Message struct {
	ID string `json:"id"`
	// Sequential number assigned by the server, ordered by recording time.
	Number         int    `json:"number"`
	Sender         string `json:"sender"`
	SenderDetail   string `json:"senderDetail"`
	Receiver       string `json:"receiver"`
	ReceiverDetail string `json:"receiverDetail"`
	Content        string `json:"content"`
	Medium         Medium `json:"medium"`
	// Operator-supplied communication time (may differ from createdAt).
	Time      time.Time      `json:"time"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
	Triage    TriageStatus   `json:"triage"`
	Priority  PriorityStatus `json:"priority"`
	// Divisions this message has been triaged to (flat — no join-table wrapper).
	Divisions []*Division `json:"divisions"`
}

type Mutation struct {
}

type Query struct {
}

type TriageMessageInput struct {
	Triage   TriageStatus   `json:"triage"`
	Priority PriorityStatus `json:"priority"`
	// IDs of divisions to assign to this message (replaces current set).
	DivisionIds []string `json:"divisionIds"`
}

type UpdateIncidentInput struct {
	Name      *string          `json:"name,omitempty"`
	Location  *string          `json:"location,omitempty"`
	Divisions []*DivisionInput `json:"divisions,omitempty"`
}

type UpdateMessageInput struct {
	Sender         *string    `json:"sender,omitempty"`
	Receiver       *string    `json:"receiver,omitempty"`
	SenderDetail   *string    `json:"senderDetail,omitempty"`
	ReceiverDetail *string    `json:"receiverDetail,omitempty"`
	Content        *string    `json:"content,omitempty"`
	Medium         *Medium    `json:"medium,omitempty"`
	Time           *time.Time `json:"time,omitempty"`
}

type Medium string

const (
	MediumRadio Medium = "RADIO"
	MediumPhone Medium = "PHONE"
	MediumEmail Medium = "EMAIL"
	MediumOther Medium = "OTHER"
)

var AllMedium = []Medium{
	MediumRadio,
	MediumPhone,
	MediumEmail,
	MediumOther,
}

func (e Medium) IsValid() bool {
	switch e {
	case MediumRadio, MediumPhone, MediumEmail, MediumOther:
		return true
	}
	return false
}

func (e Medium) String() string {
	return string(e)
}

func (e *Medium) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Medium(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Medium", str)
	}
	return nil
}

func (e Medium) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Medium) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Medium) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PriorityStatus string

const (
	PriorityStatusNormal PriorityStatus = "NORMAL"
	PriorityStatusHigh   PriorityStatus = "HIGH"
)

var AllPriorityStatus = []PriorityStatus{
	PriorityStatusNormal,
	PriorityStatusHigh,
}

func (e PriorityStatus) IsValid() bool {
	switch e {
	case PriorityStatusNormal, PriorityStatusHigh:
		return true
	}
	return false
}

func (e PriorityStatus) String() string {
	return string(e)
}

func (e *PriorityStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PriorityStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PriorityStatus", str)
	}
	return nil
}

func (e PriorityStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PriorityStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PriorityStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TriageStatus string

const (
	TriageStatusPending  TriageStatus = "PENDING"
	TriageStatusDone     TriageStatus = "DONE"
	TriageStatusMoreinfo TriageStatus = "MOREINFO"
	TriageStatusReset    TriageStatus = "RESET"
)

var AllTriageStatus = []TriageStatus{
	TriageStatusPending,
	TriageStatusDone,
	TriageStatusMoreinfo,
	TriageStatusReset,
}

func (e TriageStatus) IsValid() bool {
	switch e {
	case TriageStatusPending, TriageStatusDone, TriageStatusMoreinfo, TriageStatusReset:
		return true
	}
	return false
}

func (e TriageStatus) String() string {
	return string(e)
}

func (e *TriageStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TriageStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TriageStatus", str)
	}
	return nil
}

func (e TriageStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TriageStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TriageStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
