package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"

	"github.com/f-eld-ch/sitrep/internal/adapter/inbound/graphql/generated"
	"github.com/f-eld-ch/sitrep/internal/adapter/inbound/graphql/model"
	"github.com/f-eld-ch/sitrep/internal/adapter/inbound/graphql/scalar"
	"github.com/f-eld-ch/sitrep/internal/core/domain/incident"
	"github.com/f-eld-ch/sitrep/internal/core/domain/shared"
	"github.com/f-eld-ch/sitrep/internal/platform/identity"
	"github.com/google/uuid"
)

// Messages is the field resolver for Incident.messages.
// It is called whenever a client requests the messages field on an Incident.
func (r *incidentResolver) Messages(ctx context.Context, obj *model.Incident) ([]*model.Message, error) {
	incID, err := parseUUID(obj.ID)
	if err != nil {
		return nil, err
	}

	// Load the incident's active divisions for the tag-name lookup.
	inc, err := r.Queries.GetIncident(ctx, incID)
	if err != nil {
		return nil, err
	}
	divIndex := divisionsByID(inc.Divisions)

	rows, err := r.Queries.ListMessages(ctx, incID)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Message, len(rows))
	for i, row := range rows {
		out[i] = messageRMToModel(row, divIndex)
	}
	return out, nil
}

// CreateIncident is the resolver for the createIncident field.
func (r *mutationResolver) CreateIncident(ctx context.Context, input model.CreateIncidentInput) (*model.Incident, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return nil, err
	}

	var loc *incident.LocationData
	if input.Location != nil && *input.Location != "" {
		loc = &incident.LocationData{Name: *input.Location}
	}

	divisions := make([]incident.DivisionData, len(input.Divisions))
	for i, d := range input.Divisions {
		divisions[i] = incident.DivisionData{Name: d.Name, Description: d.Description}
	}

	layerNames := make([]string, len(input.Layers))
	for i, l := range input.Layers {
		layerNames[i] = l.Name
	}

	result, err := r.Incidents.CreateIncident(ctx, input.Name, loc, divisions, layerNames, actor)
	if err != nil {
		return nil, err
	}
	return incidentResultToModel(result), nil
}

// UpdateIncident is the resolver for the updateIncident field.
func (r *mutationResolver) UpdateIncident(ctx context.Context, id string, input model.UpdateIncidentInput) (*model.Incident, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return nil, err
	}
	incID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}

	var loc *incident.LocationData
	if input.Location != nil {
		if *input.Location != "" {
			loc = &incident.LocationData{Name: *input.Location}
		} else {
			loc = &incident.LocationData{} // empty = clear location
		}
	}

	var divisions []incident.DivisionData
	if input.Divisions != nil {
		divisions = make([]incident.DivisionData, len(input.Divisions))
		for i, d := range input.Divisions {
			var divID shared.DivisionID
			if d.ID != nil {
				u, err := parseUUID(*d.ID)
				if err != nil {
					return nil, err
				}
				divID = shared.DivisionID(u)
			}
			divisions[i] = incident.DivisionData{ID: divID, Name: d.Name, Description: d.Description}
		}
	}

	state, err := r.Incidents.UpdateIncident(ctx, shared.IncidentID(incID), input.Name, loc, divisions, actor)
	if err != nil {
		return nil, err
	}
	return incidentStateToModel(state), nil
}

// CloseIncident is the resolver for the closeIncident field.
func (r *mutationResolver) CloseIncident(ctx context.Context, id string) (*model.Incident, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return nil, err
	}
	incID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}
	state, err := r.Incidents.CloseIncident(ctx, shared.IncidentID(incID), actor)
	if err != nil {
		return nil, err
	}
	return incidentStateToModel(state), nil
}

// ReopenIncident is the resolver for the reopenIncident field.
func (r *mutationResolver) ReopenIncident(ctx context.Context, id string) (*model.Incident, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return nil, err
	}
	incID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}
	state, err := r.Incidents.ReopenIncident(ctx, shared.IncidentID(incID), actor)
	if err != nil {
		return nil, err
	}
	return incidentStateToModel(state), nil
}

// DeleteIncident is the resolver for the deleteIncident field.
func (r *mutationResolver) DeleteIncident(ctx context.Context, id string) (string, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return "", err
	}
	incID, err := parseUUID(id)
	if err != nil {
		return "", err
	}
	if err := r.Incidents.DeleteIncident(ctx, shared.IncidentID(incID), actor); err != nil {
		return "", err
	}
	return id, nil
}

// CreateMessage is the resolver for the createMessage field.
func (r *mutationResolver) CreateMessage(ctx context.Context, input model.CreateMessageInput) (*model.Message, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return nil, err
	}
	incID, err := parseUUID(input.IncidentID)
	if err != nil {
		return nil, err
	}
	medium, err := modelMediumToDomain(input.Medium)
	if err != nil {
		return nil, fmt.Errorf("%w: %v", shared.ErrInvalidInput, err)
	}

	state, err := r.Messages.RecordMessage(ctx,
		shared.IncidentID(incID),
		input.Content, input.Sender, input.SenderDetail,
		input.Receiver, input.ReceiverDetail,
		medium, input.Time, actor)
	if err != nil {
		return nil, err
	}
	return messageStateToModel(state), nil
}

// UpdateMessage is the resolver for the updateMessage field.
func (r *mutationResolver) UpdateMessage(ctx context.Context, id string, input model.UpdateMessageInput) (*model.Message, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return nil, err
	}
	msgID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}

	var medium *shared.Medium
	if input.Medium != nil {
		m, err := modelMediumToDomain(*input.Medium)
		if err != nil {
			return nil, fmt.Errorf("%w: %v", shared.ErrInvalidInput, err)
		}
		medium = &m
	}

	state, err := r.Messages.CorrectMessage(ctx, shared.MessageID(msgID),
		input.Content, input.Sender, input.SenderDetail,
		input.Receiver, input.ReceiverDetail,
		medium, input.Time, actor)
	if err != nil {
		return nil, err
	}
	msg := messageStateToModel(state)
	if len(state.DivisionIDs) > 0 {
		inc, lookupErr := r.Queries.GetIncident(ctx, uuid.UUID(state.IncidentID))
		if lookupErr == nil {
			divIndex := divisionsByID(inc.Divisions)
			for _, divID := range state.DivisionIDs {
				if d, ok := divIndex[uuid.UUID(divID)]; ok {
					msg.Divisions = append(msg.Divisions, divisionRMToModel(d))
				}
			}
		}
	}
	return msg, nil
}

// TriageMessage is the resolver for the triageMessage field.
func (r *mutationResolver) TriageMessage(ctx context.Context, id string, input model.TriageMessageInput) (*model.Message, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return nil, err
	}
	msgID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}
	triage, err := modelTriageToDomain(input.Triage)
	if err != nil {
		return nil, fmt.Errorf("%w: %v", shared.ErrInvalidInput, err)
	}
	priority, err := modelPriorityToDomain(input.Priority)
	if err != nil {
		return nil, fmt.Errorf("%w: %v", shared.ErrInvalidInput, err)
	}

	divisionIDs := make([]shared.DivisionID, len(input.DivisionIds))
	for i, rawID := range input.DivisionIds {
		u, err := parseUUID(rawID)
		if err != nil {
			return nil, err
		}
		divisionIDs[i] = shared.DivisionID(u)
	}

	state, err := r.Messages.TriageMessage(ctx, shared.MessageID(msgID), triage, priority, divisionIDs, actor)
	if err != nil {
		return nil, err
	}
	msg := messageStateToModel(state)
	// Divisions on a message are incident-level references (stable, no projection race).
	// Look them up so the mutation response contains full name/description data.
	if len(state.DivisionIDs) > 0 {
		inc, lookupErr := r.Queries.GetIncident(ctx, uuid.UUID(state.IncidentID))
		if lookupErr == nil {
			divIndex := divisionsByID(inc.Divisions)
			for _, divID := range state.DivisionIDs {
				if d, ok := divIndex[uuid.UUID(divID)]; ok {
					msg.Divisions = append(msg.Divisions, divisionRMToModel(d))
				}
			}
		}
	}
	return msg, nil
}

// DeleteMessage is the resolver for the deleteMessage field.
func (r *mutationResolver) DeleteMessage(ctx context.Context, id string) (string, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return "", err
	}
	msgID, err := parseUUID(id)
	if err != nil {
		return "", err
	}
	if err := r.Messages.DeleteMessage(ctx, shared.MessageID(msgID), actor); err != nil {
		return "", err
	}
	return id, nil
}

// CreateLayer is the resolver for the createLayer field.
func (r *mutationResolver) CreateLayer(ctx context.Context, incidentID string, name string) (*model.Layer, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return nil, err
	}
	incID, err := parseUUID(incidentID)
	if err != nil {
		return nil, err
	}
	layerID, err := r.Layers.CreateLayer(ctx, shared.IncidentID(incID), name, actor)
	if err != nil {
		return nil, err
	}
	return &model.Layer{
		ID:       uuid.UUID(layerID).String(),
		Name:     name,
		Revision: 0,
		Features: []*model.Feature{},
	}, nil
}

// AddFeature is the resolver for the addFeature field.
func (r *mutationResolver) AddFeature(ctx context.Context, incidentID string, layerID string, id string, geometry scalar.JSONMap, properties scalar.JSONMap) (*model.Feature, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return nil, err
	}
	featureID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}
	incID, err := parseUUID(incidentID)
	if err != nil {
		return nil, err
	}
	layID, err := parseUUID(layerID)
	if err != nil {
		return nil, err
	}
	if err := r.Features.PlaceFeature(ctx,
		shared.FeatureID(featureID), shared.IncidentID(incID), shared.LayerID(layID),
		geometry, properties, actor); err != nil {
		return nil, err
	}
	return &model.Feature{ID: id, Geometry: geometry, Properties: properties}, nil
}

// ModifyFeature is the resolver for the modifyFeature field.
func (r *mutationResolver) ModifyFeature(ctx context.Context, id string, geometry scalar.JSONMap, properties scalar.JSONMap) (*model.Feature, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return nil, err
	}
	featureID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}
	state, err := r.Features.ModifyFeature(ctx, shared.FeatureID(featureID), geometry, properties, actor)
	if err != nil {
		return nil, err
	}
	// Return the full aggregate state so Apollo receives both geometry and
	// properties even for sparse updates — prevents null from overwriting the
	// unchanged cached field.
	return &model.Feature{
		ID:         id,
		Geometry:   scalar.JSONMap(state.Geometry),
		Properties: scalar.JSONMap(state.Properties),
	}, nil
}

// DeleteFeature is the resolver for the deleteFeature field.
func (r *mutationResolver) DeleteFeature(ctx context.Context, id string) (string, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return "", err
	}
	featureID, err := parseUUID(id)
	if err != nil {
		return "", err
	}
	if err := r.Features.RemoveFeature(ctx, shared.FeatureID(featureID), actor); err != nil {
		return "", err
	}
	return id, nil
}

// Incidents is the resolver for the incidents field.
func (r *queryResolver) Incidents(ctx context.Context) ([]*model.Incident, error) {
	rows, err := r.Queries.ListIncidents(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Incident, len(rows))
	for i, row := range rows {
		out[i] = incidentRMToModel(row)
	}
	return out, nil
}

// Incident is the resolver for the incident field.
func (r *queryResolver) Incident(ctx context.Context, id string) (*model.Incident, error) {
	incID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}
	row, err := r.Queries.GetIncident(ctx, incID)
	if err != nil {
		return nil, err
	}
	return incidentRMToModel(row), nil
}

// Message is the resolver for the message field.
func (r *queryResolver) Message(ctx context.Context, id string) (*model.Message, error) {
	msgID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}
	return r.loadMessage(ctx, msgID)
}

// LayersForIncident is the resolver for the layersForIncident field.
func (r *queryResolver) LayersForIncident(ctx context.Context, incidentID string) ([]*model.Layer, error) {
	incID, err := parseUUID(incidentID)
	if err != nil {
		return nil, err
	}
	rows, err := r.Queries.ListLayers(ctx, incID)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Layer, 0, len(rows))
	for _, row := range rows {
		layer, err := layerRMToModel(row)
		if err != nil {
			return nil, err
		}
		out = append(out, layer)
	}
	return out, nil
}

// Incident returns generated.IncidentResolver implementation.
func (r *Resolver) Incident() generated.IncidentResolver { return &incidentResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type (
	incidentResolver struct{ *Resolver }
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
