package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"

	"github.com/google/uuid"

	"github.com/f-eld-ch/sitrep/internal/adapter/inbound/graphql/generated"
	"github.com/f-eld-ch/sitrep/internal/adapter/inbound/graphql/model"
	"github.com/f-eld-ch/sitrep/internal/adapter/inbound/graphql/scalar"
	"github.com/f-eld-ch/sitrep/internal/core/domain/access"
	"github.com/f-eld-ch/sitrep/internal/core/domain/incident"
	"github.com/f-eld-ch/sitrep/internal/core/domain/shared"
	"github.com/f-eld-ch/sitrep/internal/platform/identity"
)

// ChildIncidents is the resolver for the childIncidents field.
func (r *incidentResolver) ChildIncidents(ctx context.Context, obj *model.Incident) ([]*model.Incident, error) {
	incID, err := parseUUID(obj.ID)
	if err != nil {
		return nil, err
	}

	rows, err := r.Queries.ListChildIncidents(ctx, incID)
	if err != nil {
		return nil, err
	}

	out := make([]*model.Incident, len(rows))
	for i, row := range rows {
		out[i] = incidentRMToModel(row)
	}

	return out, nil
}

// Messages is the field resolver for Incident.messages.
// It is called whenever a client requests the messages field on an Incident.
func (r *incidentResolver) Messages(ctx context.Context, obj *model.Incident) ([]*model.Message, error) {
	incID, err := parseUUID(obj.ID)
	if err != nil {
		return nil, err
	}

	// Load the incident's active divisions for the tag-name lookup.
	inc, err := r.Queries.GetIncident(ctx, incID)
	if err != nil {
		return nil, err
	}

	divIndex := divisionsByID(inc.Divisions)

	rows, err := r.Queries.ListMessages(ctx, incID)
	if err != nil {
		return nil, err
	}

	out := make([]*model.Message, len(rows))
	for i, row := range rows {
		out[i] = messageRMToModel(row, divIndex)
	}

	return out, nil
}

// CreateIncident is the resolver for the createIncident field.
func (r *mutationResolver) CreateIncident(
	ctx context.Context,
	input model.CreateIncidentInput,
) (*model.Incident, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return nil, err
	}

	var parentID *shared.IncidentID

	if input.ParentID != nil {
		u, err := parseUUID(*input.ParentID)
		if err != nil {
			return nil, err
		}

		id := shared.IncidentID(u)
		parentID = &id
	}

	var loc *incident.LocationData
	if input.Location != nil && *input.Location != "" {
		loc = &incident.LocationData{Name: *input.Location}
	}

	divisions := make([]incident.DivisionData, len(input.Divisions))
	for i, d := range input.Divisions {
		divisions[i] = incident.DivisionData{Name: d.Name, Description: d.Description}
	}

	layerNames := make([]string, len(input.Layers))
	for i, l := range input.Layers {
		layerNames[i] = l.Name
	}

	mode := access.OpenOperational
	if input.Mode != nil {
		mode = accessModeToDomain(*input.Mode)
	}

	result, err := r.Incidents.CreateIncidentWithParentMode(
		ctx, input.Name, loc, divisions, layerNames, parentID, mode, actor,
	)
	if err != nil {
		return nil, err
	}

	return incidentResultToModel(result), nil
}

// ChangeIncidentAccessMode is the resolver for the changeIncidentAccessMode field.
func (r *mutationResolver) ChangeIncidentAccessMode(
	ctx context.Context,
	incidentID string,
	mode model.IncidentAccessMode,
) (*model.IncidentAccessGrant, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return nil, err
	}

	id, err := parseUUID(incidentID)
	if err != nil {
		return nil, err
	}

	if r.Access == nil {
		return nil, shared.ErrForbidden
	}

	if err := r.Access.ChangeIncidentAccessMode(
		ctx,
		shared.IncidentID(id),
		accessModeToDomain(mode),
		actor,
	); err != nil {
		return nil, err
	}

	return &model.IncidentAccessGrant{
		IncidentID:    incidentID,
		PrincipalKind: model.AccessPrincipalKindUser,
		PrincipalID:   actor.Sub,
		Role:          model.IncidentRoleOwner,
	}, nil
}

// GrantIncidentRole is the resolver for the grantIncidentRole field.
func (r *mutationResolver) GrantIncidentRole(
	ctx context.Context,
	incidentID string,
	principalKind model.AccessPrincipalKind,
	principalID string,
	role model.IncidentRole,
) (*model.IncidentAccessGrant, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return nil, err
	}

	id, err := parseUUID(incidentID)
	if err != nil {
		return nil, err
	}

	if r.Access == nil {
		return nil, shared.ErrForbidden
	}

	principal := access.Principal{Kind: principalKindToDomain(principalKind), ID: principalID}
	if err := r.Access.GrantIncidentRole(
		ctx,
		shared.IncidentID(id),
		principal,
		incidentRoleToDomain(role),
		actor,
	); err != nil {
		return nil, err
	}

	return &model.IncidentAccessGrant{
		IncidentID:    incidentID,
		PrincipalKind: principalKind,
		PrincipalID:   principalID,
		Role:          role,
	}, nil
}

// RevokeIncidentRole is the resolver for the revokeIncidentRole field.
func (r *mutationResolver) RevokeIncidentRole(
	ctx context.Context,
	incidentID string,
	principalKind model.AccessPrincipalKind,
	principalID string,
	role model.IncidentRole,
) (string, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return "", err
	}

	id, err := parseUUID(incidentID)
	if err != nil {
		return "", err
	}

	if r.Access == nil {
		return "", shared.ErrForbidden
	}

	if err := r.Access.RevokeIncidentRole(
		ctx,
		shared.IncidentID(id),
		access.Principal{Kind: principalKindToDomain(principalKind), ID: principalID},
		incidentRoleToDomain(role),
		actor,
	); err != nil {
		return "", err
	}

	return incidentID, nil
}

// CreateAccessGroup is the resolver for the createAccessGroup field.
func (r *mutationResolver) CreateAccessGroup(
	ctx context.Context,
	name string,
	description string,
) (*model.AccessGroup, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return nil, err
	}

	if r.Access == nil {
		return nil, shared.ErrForbidden
	}

	id, err := r.Access.CreateAccessGroup(ctx, name, description, actor)
	if err != nil {
		return nil, err
	}

	return &model.AccessGroup{ID: id.String(), Name: name, Description: description}, nil
}

// RenameAccessGroup is the resolver for the renameAccessGroup field.
func (r *mutationResolver) RenameAccessGroup(
	ctx context.Context,
	groupID string,
	name string,
) (*model.AccessGroup, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return nil, err
	}

	id, err := parseUUID(groupID)
	if err != nil {
		return nil, err
	}

	if r.Access == nil {
		return nil, shared.ErrForbidden
	}

	if err := r.Access.RenameAccessGroup(ctx, id, name, actor); err != nil {
		return nil, err
	}

	return &model.AccessGroup{ID: groupID, Name: name}, nil
}

// UpdateAccessGroupDescription is the resolver for the updateAccessGroupDescription field.
func (r *mutationResolver) UpdateAccessGroupDescription(
	ctx context.Context,
	groupID string,
	description string,
) (*model.AccessGroup, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return nil, err
	}

	id, err := parseUUID(groupID)
	if err != nil {
		return nil, err
	}

	if r.Access == nil {
		return nil, shared.ErrForbidden
	}

	if err := r.Access.UpdateAccessGroupDescription(ctx, id, description, actor); err != nil {
		return nil, err
	}

	return &model.AccessGroup{ID: groupID, Description: description}, nil
}

// ArchiveAccessGroup is the resolver for the archiveAccessGroup field.
func (r *mutationResolver) ArchiveAccessGroup(ctx context.Context, groupID string) (string, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return "", err
	}

	id, err := parseUUID(groupID)
	if err != nil {
		return "", err
	}

	if r.Access == nil {
		return "", shared.ErrForbidden
	}

	if err := r.Access.ArchiveAccessGroup(ctx, id, actor); err != nil {
		return "", err
	}

	return groupID, nil
}

// AddGroupMember is the resolver for the addGroupMember field.
func (r *mutationResolver) AddGroupMember(ctx context.Context, groupID string, subject string) (string, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return "", err
	}

	id, err := parseUUID(groupID)
	if err != nil {
		return "", err
	}

	if r.Access == nil {
		return "", shared.ErrForbidden
	}

	if err := r.Access.AddGroupMember(ctx, id, subject, actor); err != nil {
		return "", err
	}

	return groupID, nil
}

// RemoveGroupMember is the resolver for the removeGroupMember field.
func (r *mutationResolver) RemoveGroupMember(ctx context.Context, groupID string, subject string) (string, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return "", err
	}

	id, err := parseUUID(groupID)
	if err != nil {
		return "", err
	}

	if r.Access == nil {
		return "", shared.ErrForbidden
	}

	if err := r.Access.RemoveGroupMember(ctx, id, subject, actor); err != nil {
		return "", err
	}

	return groupID, nil
}

// GrantGlobalRole is the resolver for the grantGlobalRole field.
func (r *mutationResolver) GrantGlobalRole(ctx context.Context, subject string, role model.GlobalRole) (string, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return "", err
	}

	if r.Access == nil {
		return "", shared.ErrForbidden
	}
	if err := r.Access.GrantGlobalRole(ctx, subject, globalRoleToDomain(role), actor); err != nil {
		return "", err
	}

	return subject, nil
}

// RevokeGlobalRole is the resolver for the revokeGlobalRole field.
func (r *mutationResolver) RevokeGlobalRole(
	ctx context.Context,
	subject string,
	role model.GlobalRole,
) (string, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return "", err
	}

	if r.Access == nil {
		return "", shared.ErrForbidden
	}
	if err := r.Access.RevokeGlobalRole(ctx, subject, globalRoleToDomain(role), actor); err != nil {
		return "", err
	}

	return subject, nil
}

// UpdateIncident is the resolver for the updateIncident field.
func (r *mutationResolver) UpdateIncident(
	ctx context.Context,
	id string,
	input model.UpdateIncidentInput,
) (*model.Incident, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return nil, err
	}

	incID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}

	var loc *incident.LocationData

	if input.Location != nil {
		if *input.Location != "" {
			loc = &incident.LocationData{Name: *input.Location}
		} else {
			loc = &incident.LocationData{} // empty = clear location
		}
	}

	var divisions []incident.DivisionData
	if input.Divisions != nil {
		divisions = make([]incident.DivisionData, len(input.Divisions))
		for i, d := range input.Divisions {
			var divID shared.DivisionID

			if d.ID != nil {
				u, err := parseUUID(*d.ID)
				if err != nil {
					return nil, err
				}

				divID = shared.DivisionID(u)
			}

			divisions[i] = incident.DivisionData{ID: divID, Name: d.Name, Description: d.Description}
		}
	}

	state, err := r.Incidents.UpdateIncident(ctx, shared.IncidentID(incID), input.Name, loc, divisions, actor)
	if err != nil {
		return nil, err
	}

	return incidentStateToModel(state), nil
}

// CloseIncident is the resolver for the closeIncident field.
func (r *mutationResolver) CloseIncident(ctx context.Context, id string) (*model.Incident, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return nil, err
	}

	incID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}

	state, err := r.Incidents.CloseIncident(ctx, shared.IncidentID(incID), actor)
	if err != nil {
		return nil, err
	}

	return incidentStateToModel(state), nil
}

// ReopenIncident is the resolver for the reopenIncident field.
func (r *mutationResolver) ReopenIncident(ctx context.Context, id string) (*model.Incident, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return nil, err
	}

	incID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}

	state, err := r.Incidents.ReopenIncident(ctx, shared.IncidentID(incID), actor)
	if err != nil {
		return nil, err
	}

	return incidentStateToModel(state), nil
}

// DeleteIncident is the resolver for the deleteIncident field.
func (r *mutationResolver) DeleteIncident(ctx context.Context, id string) (string, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return "", err
	}

	incID, err := parseUUID(id)
	if err != nil {
		return "", err
	}

	if err := r.Incidents.DeleteIncident(ctx, shared.IncidentID(incID), actor); err != nil {
		return "", err
	}

	return id, nil
}

// LinkIncidentParent is the resolver for the linkIncidentParent field.
func (r *mutationResolver) LinkIncidentParent(
	ctx context.Context,
	childID string,
	parentID string,
) (*model.Incident, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return nil, err
	}

	childUUID, err := parseUUID(childID)
	if err != nil {
		return nil, err
	}

	parentUUID, err := parseUUID(parentID)
	if err != nil {
		return nil, err
	}

	state, err := r.Incidents.LinkIncidentParent(
		ctx,
		shared.IncidentID(childUUID),
		shared.IncidentID(parentUUID),
		actor,
	)
	if err != nil {
		return nil, err
	}

	return incidentStateToModel(state), nil
}

// UnlinkIncidentParent is the resolver for the unlinkIncidentParent field.
func (r *mutationResolver) UnlinkIncidentParent(ctx context.Context, childID string) (*model.Incident, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return nil, err
	}

	childUUID, err := parseUUID(childID)
	if err != nil {
		return nil, err
	}

	state, err := r.Incidents.UnlinkIncidentParent(ctx, shared.IncidentID(childUUID), actor)
	if err != nil {
		return nil, err
	}

	return incidentStateToModel(state), nil
}

// CreateMessage is the resolver for the createMessage field.
func (r *mutationResolver) CreateMessage(ctx context.Context, input model.CreateMessageInput) (*model.Message, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return nil, err
	}

	incID, err := parseUUID(input.IncidentID)
	if err != nil {
		return nil, err
	}

	medium, err := modelMediumToDomain(input.Medium)
	if err != nil {
		return nil, fmt.Errorf("%w: %w", shared.ErrInvalidInput, err)
	}

	state, err := r.Messages.RecordMessage(ctx,
		shared.IncidentID(incID),
		input.Content, input.Sender, input.SenderDetail,
		input.Receiver, input.ReceiverDetail,
		medium, input.Time, actor)
	if err != nil {
		return nil, err
	}

	return messageStateToModel(state), nil
}

// UpdateMessage is the resolver for the updateMessage field.
func (r *mutationResolver) UpdateMessage(
	ctx context.Context,
	id string,
	input model.UpdateMessageInput,
) (*model.Message, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return nil, err
	}

	msgID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}

	msg, err := r.Queries.GetMessage(ctx, msgID)
	if err != nil {
		return nil, err
	}

	if r.IncidentAccessChecker != nil {
		allowed, err := r.IncidentAccessChecker.Can(ctx, actor.Sub, shared.IncidentID(msg.IncidentID), access.IncidentWrite)
		if err != nil {
			return nil, err
		}

		if !allowed {
			return nil, shared.ErrForbidden
		}
	}

	var medium *shared.Medium

	if input.Medium != nil {
		m, err := modelMediumToDomain(*input.Medium)
		if err != nil {
			return nil, fmt.Errorf("%w: %w", shared.ErrInvalidInput, err)
		}

		medium = &m
	}

	state, err := r.Messages.CorrectMessage(ctx, shared.MessageID(msgID),
		input.Content, input.Sender, input.SenderDetail,
		input.Receiver, input.ReceiverDetail,
		medium, input.Time, actor)
	if err != nil {
		return nil, err
	}
	// UPDATE_MESSAGE does not request divisions; Apollo retains the cached value.
	return messageStateToModel(state), nil
}

// TriageMessage is the resolver for the triageMessage field.
func (r *mutationResolver) TriageMessage(
	ctx context.Context,
	id string,
	input model.TriageMessageInput,
) (*model.Message, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return nil, err
	}

	msgID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}

	triageMsg, err := r.Queries.GetMessage(ctx, msgID)
	if err != nil {
		return nil, err
	}

	if r.IncidentAccessChecker != nil {
		allowed, err := r.IncidentAccessChecker.Can(ctx, actor.Sub, shared.IncidentID(triageMsg.IncidentID), access.IncidentWrite)
		if err != nil {
			return nil, err
		}

		if !allowed {
			return nil, shared.ErrForbidden
		}
	}

	triage, err := modelTriageToDomain(input.Triage)
	if err != nil {
		return nil, fmt.Errorf("%w: %w", shared.ErrInvalidInput, err)
	}

	priority, err := modelPriorityToDomain(input.Priority)
	if err != nil {
		return nil, fmt.Errorf("%w: %w", shared.ErrInvalidInput, err)
	}

	divisionIDs := make([]shared.DivisionID, len(input.DivisionIds))
	for i, rawID := range input.DivisionIds {
		u, err := parseUUID(rawID)
		if err != nil {
			return nil, err
		}

		divisionIDs[i] = shared.DivisionID(u)
	}

	state, err := r.Messages.TriageMessage(
		ctx,
		shared.MessageID(msgID),
		triage,
		priority,
		divisionIDs,
		actor,
	)
	if err != nil {
		return nil, err
	}

	msg := messageStateToModel(state)
	// Divisions on a message are incident-level references (stable, no projection race).
	// Look them up so the mutation response contains full name/description data.
	if len(state.DivisionIDs) > 0 {
		inc, lookupErr := r.Queries.GetIncident(ctx, uuid.UUID(state.IncidentID))
		if lookupErr == nil {
			divIndex := divisionsByID(inc.Divisions)
			for _, divID := range state.DivisionIDs {
				if d, ok := divIndex[uuid.UUID(divID)]; ok {
					msg.Divisions = append(msg.Divisions, divisionRMToModel(d))
				}
			}
		}
	}

	return msg, nil
}

// DeleteMessage is the resolver for the deleteMessage field.
func (r *mutationResolver) DeleteMessage(ctx context.Context, id string) (string, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return "", err
	}

	msgID, err := parseUUID(id)
	if err != nil {
		return "", err
	}

	delMsg, err := r.Queries.GetMessage(ctx, msgID)
	if err != nil {
		return "", err
	}

	if r.IncidentAccessChecker != nil {
		allowed, err := r.IncidentAccessChecker.Can(ctx, actor.Sub, shared.IncidentID(delMsg.IncidentID), access.IncidentWrite)
		if err != nil {
			return "", err
		}

		if !allowed {
			return "", shared.ErrForbidden
		}
	}

	if err := r.Messages.DeleteMessage(ctx, shared.MessageID(msgID), actor); err != nil {
		return "", err
	}

	return id, nil
}

// CreateLayer is the resolver for the createLayer field.
func (r *mutationResolver) CreateLayer(ctx context.Context, incidentID string, name string) (*model.Layer, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return nil, err
	}

	incID, err := parseUUID(incidentID)
	if err != nil {
		return nil, err
	}

	inc, err := r.Incidents.LoadIncident(ctx, shared.IncidentID(incID))
	if err != nil {
		return nil, err
	}

	layerID, err := r.Layers.CreateLayer(ctx, shared.IncidentID(incID), name, actor)
	if err != nil {
		return nil, err
	}

	return &model.Layer{
		ID:                 uuid.UUID(layerID).String(),
		SourceIncidentID:   incidentID,
		SourceIncidentName: inc.Name(),
		Name:               name,
		Revision:           0,
		Features:           []*model.Feature{},
	}, nil
}

// AddFeature is the resolver for the addFeature field.
func (r *mutationResolver) AddFeature(
	ctx context.Context,
	incidentID string,
	layerID string,
	id string,
	geometry scalar.JSONMap,
	properties scalar.JSONMap,
) (*model.Feature, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return nil, err
	}

	featureID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}

	incID, err := parseUUID(incidentID)
	if err != nil {
		return nil, err
	}

	layID, err := parseUUID(layerID)
	if err != nil {
		return nil, err
	}

	if err := r.Features.PlaceFeature(ctx,
		shared.FeatureID(featureID), shared.IncidentID(incID), shared.LayerID(layID),
		geometry, properties, actor); err != nil {
		return nil, err
	}

	return &model.Feature{ID: id, Geometry: geometry, Properties: properties}, nil
}

// ModifyFeature is the resolver for the modifyFeature field.
func (r *mutationResolver) ModifyFeature(
	ctx context.Context,
	id string,
	geometry scalar.JSONMap,
	properties scalar.JSONMap,
) (*model.Feature, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return nil, err
	}

	featureID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}

	if r.IncidentAccessChecker != nil {
		featureIncID, err := r.Queries.GetFeatureIncidentID(ctx, featureID)
		if err != nil {
			return nil, err
		}

		allowed, err := r.IncidentAccessChecker.Can(ctx, actor.Sub, shared.IncidentID(featureIncID), access.IncidentWrite)
		if err != nil {
			return nil, err
		}

		if !allowed {
			return nil, shared.ErrForbidden
		}
	}

	state, err := r.Features.ModifyFeature(ctx, shared.FeatureID(featureID), geometry, properties, actor)
	if err != nil {
		return nil, err
	}
	// Return the full aggregate state so Apollo receives both geometry and
	// properties even for sparse updates — prevents null from overwriting the
	// unchanged cached field.
	return &model.Feature{
		ID:         id,
		Geometry:   scalar.JSONMap(state.Geometry),
		Properties: scalar.JSONMap(state.Properties),
	}, nil
}

// DeleteFeature is the resolver for the deleteFeature field.
func (r *mutationResolver) DeleteFeature(ctx context.Context, id string) (string, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return "", err
	}

	featureID, err := parseUUID(id)
	if err != nil {
		return "", err
	}

	if r.IncidentAccessChecker != nil {
		featureIncID, err := r.Queries.GetFeatureIncidentID(ctx, featureID)
		if err != nil {
			return "", err
		}

		allowed, err := r.IncidentAccessChecker.Can(ctx, actor.Sub, shared.IncidentID(featureIncID), access.IncidentWrite)
		if err != nil {
			return "", err
		}

		if !allowed {
			return "", shared.ErrForbidden
		}
	}

	if err := r.Features.RemoveFeature(ctx, shared.FeatureID(featureID), actor); err != nil {
		return "", err
	}

	return id, nil
}

// Incidents is the resolver for the incidents field.
func (r *queryResolver) Incidents(ctx context.Context) ([]*model.Incident, error) {
	rows, err := r.Queries.ListIncidents(ctx)
	if err != nil {
		return nil, err
	}

	out := make([]*model.Incident, len(rows))
	for i, row := range rows {
		out[i] = incidentRMToModel(row)
	}

	return out, nil
}

// Incident is the resolver for the incident field.
func (r *queryResolver) Incident(ctx context.Context, id string) (*model.Incident, error) {
	incID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}

	row, err := r.Queries.GetIncident(ctx, incID)
	if err != nil {
		return nil, err
	}

	return incidentRMToModel(row), nil
}

// Message is the resolver for the message field.
func (r *queryResolver) Message(ctx context.Context, id string) (*model.Message, error) {
	msgID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}

	return r.loadMessage(ctx, msgID)
}

// LayersForIncident is the resolver for the layersForIncident field.
func (r *queryResolver) LayersForIncident(ctx context.Context, incidentID string) ([]*model.Layer, error) {
	incID, err := parseUUID(incidentID)
	if err != nil {
		return nil, err
	}

	rows, err := r.Queries.ListVisibleLayers(ctx, incID)
	if err != nil {
		return nil, err
	}

	out := make([]*model.Layer, 0, len(rows))
	for _, row := range rows {
		layer, err := layerRMToModel(row)
		if err != nil {
			return nil, err
		}

		out = append(out, layer)
	}

	return out, nil
}

// IncidentAccess is the resolver for the incidentAccess field.
func (r *queryResolver) IncidentAccess(ctx context.Context, incidentID string) ([]*model.IncidentAccessGrant, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return nil, err
	}
	id, err := parseUUID(incidentID)
	if err != nil {
		return nil, err
	}
	if r.AccessQueries == nil || r.Access == nil || r.IncidentAccessChecker == nil {
		return nil, shared.ErrForbidden
	}
	allowed, err := r.IncidentAccessChecker.Can(ctx, actor.Sub, shared.IncidentID(id), access.IncidentManageAccess)
	if err != nil {
		return nil, err
	}
	if !allowed {
		return nil, shared.ErrForbidden
	}
	rows, err := r.AccessQueries.ListIncidentAccess(ctx, shared.IncidentID(id))
	if err != nil {
		return nil, err
	}
	out := make([]*model.IncidentAccessGrant, 0, len(rows))
	for _, row := range rows {
		out = append(
			out,
			&model.IncidentAccessGrant{
				IncidentID:    incidentID,
				PrincipalKind: principalKindFromDomain(row.PrincipalKind),
				PrincipalID:   row.PrincipalID,
				PrincipalName: row.PrincipalName,
				Role:          incidentRoleFromDomain(row.Role),
			},
		)
	}
	return out, nil
}

// IncidentAccessMode is the resolver for the incidentAccessMode field.
func (r *queryResolver) IncidentAccessMode(ctx context.Context, incidentID string) (model.IncidentAccessMode, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return "", err
	}
	id, err := parseUUID(incidentID)
	if err != nil {
		return "", err
	}
	if r.AccessQueries == nil || r.IncidentAccessChecker == nil {
		return "", shared.ErrForbidden
	}
	allowed, err := r.IncidentAccessChecker.Can(ctx, actor.Sub, shared.IncidentID(id), access.IncidentRead)
	if err != nil {
		return "", err
	}
	if !allowed {
		return "", shared.ErrNotFound
	}
	mode, err := r.AccessQueries.GetIncidentAccessMode(ctx, shared.IncidentID(id))
	if err != nil {
		return "", err
	}

	return incidentModeFromDomain(mode), nil
}

// AccessGroups is the resolver for the accessGroups field.
func (r *queryResolver) AccessGroups(ctx context.Context) ([]*model.AccessGroup, error) {
	// Any authenticated user may list groups (names only — members require GroupManage).
	if _, err := identity.ActorFrom(ctx); err != nil {
		return nil, err
	}
	if r.AccessQueries == nil {
		return nil, shared.ErrForbidden
	}
	rows, err := r.AccessQueries.ListAccessGroups(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.AccessGroup, 0, len(rows))
	for _, row := range rows {
		out = append(out, &model.AccessGroup{
			ID:          row.ID.String(),
			Name:        row.Name,
			Description: row.Description,
			ArchivedAt:  row.ArchivedAt,
		})
	}
	return out, nil
}

// GroupMembers is the resolver for the groupMembers field.
func (r *queryResolver) GroupMembers(ctx context.Context, groupID string) ([]string, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return nil, err
	}
	if r.AccessQueries == nil || r.GlobalAccessChecker == nil {
		return nil, shared.ErrForbidden
	}
	allowed, err := r.GlobalAccessChecker.Can(ctx, actor.Sub, access.GroupManage)
	if err != nil {
		return nil, err
	}
	if !allowed {
		return nil, shared.ErrForbidden
	}
	id, err := parseUUID(groupID)
	if err != nil {
		return nil, err
	}
	rows, err := r.AccessQueries.ListGroupMembers(ctx, id)
	if err != nil {
		return nil, err
	}
	out := make([]string, 0, len(rows))
	for _, row := range rows {
		out = append(out, row.Subject)
	}
	return out, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return nil, err
	}
	if r.AccessQueries == nil || r.GlobalAccessChecker == nil {
		return nil, shared.ErrForbidden
	}
	allowed, err := r.GlobalAccessChecker.Can(ctx, actor.Sub, access.GroupManage)
	if err != nil {
		return nil, err
	}
	if !allowed {
		return nil, shared.ErrForbidden
	}
	rows, err := r.AccessQueries.ListUsers(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.User, 0, len(rows))
	for _, row := range rows {
		out = append(out, &model.User{Sub: row.Sub, Name: row.Name, Email: row.Email})
	}

	return out, nil
}

// GlobalRoles is the resolver for the globalRoles field.
func (r *queryResolver) GlobalRoles(ctx context.Context) ([]*model.GlobalRoleGrant, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return nil, err
	}
	if r.AccessQueries == nil || r.GlobalAccessChecker == nil {
		return nil, shared.ErrForbidden
	}
	allowed, err := r.GlobalAccessChecker.Can(ctx, actor.Sub, access.SystemAdminManage)
	if err != nil {
		return nil, err
	}
	if !allowed {
		return nil, shared.ErrForbidden
	}
	rows, err := r.AccessQueries.ListGlobalRoles(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.GlobalRoleGrant, 0, len(rows))
	for _, row := range rows {
		out = append(out, &model.GlobalRoleGrant{
			Subject: row.Subject,
			Role:    globalRoleFromDomain(row.Role),
			Name:    row.Name,
			Email:   row.Email,
		})
	}

	return out, nil
}

// MyGlobalRoles is the resolver for the myGlobalRoles field.
func (r *queryResolver) MyGlobalRoles(ctx context.Context) ([]*model.GlobalRoleGrant, error) {
	actor, err := identity.ActorFrom(ctx)
	if err != nil {
		return nil, err
	}
	if r.AccessQueries == nil {
		return []*model.GlobalRoleGrant{}, nil
	}
	rows, err := r.AccessQueries.MyGlobalRoles(ctx, actor.Sub)
	if err != nil {
		return nil, err
	}
	out := make([]*model.GlobalRoleGrant, 0, len(rows))
	for _, row := range rows {
		out = append(out, &model.GlobalRoleGrant{
			Subject: row.Subject,
			Role:    globalRoleFromDomain(row.Role),
			Name:    row.Name,
			Email:   row.Email,
		})
	}

	return out, nil
}

// Incident returns generated.IncidentResolver implementation.
func (r *Resolver) Incident() generated.IncidentResolver { return &incidentResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type (
	incidentResolver struct{ *Resolver }
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
