approvedGitRepositories:
  - "**"
compressionLevel: mixed
enableGlobalCache: false
enableScripts: true
enableHardenedMode: false
nodeLinker: node-modules
npmMinimalAgeGate: 0
yarnPath: .yarn/releases/yarn-4.18.0.cjs
npmScopes:
  f-eld-ch:
    npmAlwaysAuth: true
    npmMinimalAgeGate: 0
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAuthToken: "${GITHUB_TOKEN:-}"

npmRegistries:
  "https://npm.pkg.github.com":
    npmAuthToken: "${GITHUB_TOKEN:-}"
    npmAlwaysAuth: true
