/**
 * graphql-codegen config for the CURRENT Hasura schema.
 *
 * Schema source: hasura/schema/hasura.graphql — a committed SDL snapshot
 * generated by introspecting the running Hasura engine as role "editor":
 *
 *   npx graphql-codegen introspect \
 *     --url http://localhost:8080/v1/graphql \
 *     --header "x-hasura-admin-secret: <secret>" \
 *     --header "x-hasura-role: editor" \
 *     --output hasura/schema/hasura.graphql
 *
 * Introspect as "editor" (not admin) so codegen only validates documents
 * that can actually be executed at runtime.
 *
 * Committing the generated output (src/gql/) keeps CI hermetic: there is
 * no Hasura dependency in the build pipeline. The generated diff on a PR is
 * the wire-contract change, reviewable by engineers.
 *
 * Run: yarn codegen
 * Check (CI): yarn codegen:check
 */

import type { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
  schema: "../hasura/schema/hasura.graphql",
  documents: ["src/views/**/*.ts", "src/views/**/*.tsx"],
  generates: {
    "./src/gql/": {
      preset: "client",
      presetConfig: {
        fragmentMasking: false,
      },
      config: {
        useTypeImports: true,
        strictScalars: true,
        scalars: {
          uuid: "string",
          timestamptz: {
            input: "Date | string",
            output: "string",
          },
          jsonb: "Record<string, unknown>",
          MediumEnum: "string",
          PriorityStatusEnum: "string",
          TriageStatusEnum: "string",
        },
        avoidOptionals: {
          field: true,
          object: true,
          inputValue: false,
        },
        enumsAsTypes: false,
      },
    },
  },
  ignoreNoDocuments: true,
};

export default config;
