name: Auto Assign
permissions: read-all
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: 'Auto-assign issue'
      uses: pozil/auto-assign-issue@70adb98ca8b3941524e9ecde48e89067c4f96736 # v3.0.0
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: nimdanitro
          numOfAssignee: 1
