name: Automated Tests and Linting
permissions:
  contents: read
  packages: write
  id-token: write
  actions: write
on:
  push:
    branches-ignore:
      - "main"
      - "develop"
jobs:
  ui-tests:
    name: "UI Tests Only"
    uses: ./.github/workflows/ui-workflow.yml
    with:
      build: false