name: Docker Build & Push
permissions:
  contents: read
on:
  workflow_call:
    inputs:
      push:
        description: 'Whether to push the Docker images'
        required: false
        default: false
        type: boolean

jobs:
  docker:
    permissions:
      actions: write
      contents: read
      packages: write
      id-token: write
    runs-on: ubuntu-24.04-arm
    name: "Build and Push Sitrep Image"
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      
      - name: Download UI build artifacts
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: ui-build
          path: ui/build/
      
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: "stable"
      - uses: ko-build/setup-ko@d006021bd0c28d1ce33a07e7943d48b079944c8d # v0.9

      - name: Install Go dependencies
        run: go mod download

      - name: Go Test
        run: go test ./...

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
        with:
          images: ghcr.io/f-eld-ch/sitrep
          tags: |
            # set latest tag for default branch / ordered by priority
            type=semver,pattern={{version}},prefix=v,priority=920
            type=raw,value=stable,enable=${{ github.ref == format('refs/heads/{0}', 'main') }},priority=910
            type=raw,value=develop,enable={{is_default_branch}},priority=905
            # priority 900
            type=semver,pattern={{major}}.{{minor}},prefix=v
            type=semver,pattern={{major}},prefix=v
            # priority 700
            type=edge,branch=develop
            # priority 600
            type=ref,event=branch
            type=ref,event=pr,prefix=pr-,enable=true
      - name: Prepare Image Tags and Labels
        id: image_tags_labels
        run: |
          # prepare tags
          tags=""
          separator=""
          prefix=${KO_DOCKER_REPO}
          IFS=$'\n'
          for tag in ${DOCKER_METADATA_OUTPUT_TAGS}; do
            tags="$tags${separator}${tag#${prefix}:}"
            separator=","
          done
          echo "tags=$tags" >> $GITHUB_OUTPUT

          # prepare labels
          labels=""
          IFS=$'\n'
          separator=""
          for label in ${DOCKER_METADATA_OUTPUT_LABELS}; do
            labels="${labels}${separator}--image-label '$label'"
            separator=" "
          done
          echo "labels=$labels" >> $GITHUB_OUTPUT
      - name: Ko Build
        env:
          Version: ${{ steps.meta.outputs.version }}
        run: >
          ko build --bare . --tags ${{ steps.image_tags_labels.outputs.tags }} ${{ steps.image_tags_labels.outputs.labels }}