name: Docker Build & Push
permissions:
  contents: read
on:
  workflow_call:
    inputs:
      push:
        description: 'Whether to push the Docker images'
        required: false
        default: false
        type: boolean

jobs:
  docker:
    permissions:
      actions: write
      contents: read
      packages: write
      id-token: write
    runs-on: ubuntu-24.04-arm
    name: "Build and Push Sitrep Image"
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      
      - name: Download UI build artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ui-build
          path: ui/build/
      
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: "stable"
      - uses: ko-build/setup-ko@61b4d1d396f5b2e7d6bb6fefdce3dc38d1a13445 # v0.10

      - name: Install Go dependencies
        run: go mod download

      - name: Go Test
        run: go test -coverprofile=go-coverage.out ./...

      - name: Convert Go coverage to Cobertura
        run: |
          go install github.com/boumenot/gocover-cobertura@4afa1205ab3b54ae098dd4724c1657aad10f7484
          gocover-cobertura < go-coverage.out > go-cobertura.xml

      - name: Upload Go coverage artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage-report-go
          path: go-cobertura.xml

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: ghcr.io/f-eld-ch/sitrep
          tags: |
            # set latest tag for default branch / ordered by priority
            type=semver,pattern={{version}},prefix=v,priority=920
            type=raw,value=stable,enable=${{ github.ref == format('refs/heads/{0}', 'main') }},priority=910
            type=raw,value=develop,enable={{is_default_branch}},priority=905
            # priority 900
            type=semver,pattern={{major}}.{{minor}},prefix=v
            type=semver,pattern={{major}},prefix=v
            # priority 700
            type=edge,branch=develop
            # priority 600
            type=ref,event=branch
            type=ref,event=pr,prefix=pr-,enable=true
      - name: Prepare Image Tags and Labels
        id: image_tags_labels
        run: |
          # prepare tags
          tags=""
          separator=""
          prefix=${KO_DOCKER_REPO}
          IFS=$'\n'
          for tag in ${DOCKER_METADATA_OUTPUT_TAGS}; do
            tags="$tags${separator}${tag#${prefix}:}"
            separator=","
          done
          echo "tags=$tags" >> $GITHUB_OUTPUT

          # prepare labels
          labels=""
          IFS=$'\n'
          separator=""
          for label in ${DOCKER_METADATA_OUTPUT_LABELS}; do
            labels="${labels}${separator}--image-label '$label'"
            separator=" "
          done
          echo "labels=$labels" >> $GITHUB_OUTPUT
      - name: Ko Build
        env:
          Version: ${{ steps.meta.outputs.version }}
        run: >
          ko build --bare . --tags ${{ steps.image_tags_labels.outputs.tags }} ${{ steps.image_tags_labels.outputs.labels }}