name: UI Build & Test
on:
  workflow_call:
    inputs:
      build:
        description: 'Whether to build the UI'
        required: false
        default: false
        type: boolean

permissions: read-all

jobs:
  ui:
    runs-on: ubuntu-latest
    name: "UI Test and Build"
    permissions:
      actions: read
      packages: read  
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: ".nvmrc"
          cache: yarn
          cache-dependency-path: "ui/yarn.lock"
      
      - name: Extract version
        id: version
        if: inputs.build
        run: |
          # For tags, use the tag name without v prefix
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          # For branches, use branch name
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION=${GITHUB_REF#refs/heads/}
          # For pull requests, use PR number
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION=pr-${{ github.event.pull_request.number }}
          # Otherwise fallback to commit SHA
          else
            VERSION=${GITHUB_SHA::8}
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Install packages
        run: yarn install --immutable
        working-directory: ui
      
      - name: Lint ui files
        run: yarn lint
        working-directory: ui
      
      - name: Run ui tests
        run: yarn test
        working-directory: ui
      
      - name: Build ui
        if: inputs.build
        run: yarn build
        env:
          GIT_SHA: ${{ github.sha }}
          VERSION: ${{ steps.version.outputs.version }}
        working-directory: ui
      
      - name: Upload UI build artifacts
        if: inputs.build
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ui-build
          path: ui/build/
          retention-days: 1