name: UI Build & Test
on:
  workflow_call:
    inputs:
      build:
        description: 'Whether to build the UI'
        required: false
        default: false
        type: boolean

permissions: read-all

jobs:
  ui:
    runs-on: ubuntu-latest
    name: "UI Test and Build"
    permissions:
      actions: read
      packages: read  
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with: 
          fetch-depth: 0
      
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: ".nvmrc"
          cache: yarn
          cache-dependency-path: "ui/yarn.lock"
      
      - name: Install packages
        run: yarn install --immutable
        working-directory: ui
      
      - name: Lint ui files
        run: yarn lint:github
        working-directory: ui
      
      - name: Run ui tests
        run: yarn test --coverage --run
        working-directory: ui
      
      - name: Build ui
        if: inputs.build
        run: yarn build
        working-directory: ui
      
      - name: Upload UI build artifacts
        if: inputs.build
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ui-build
          path: ui/build/
          retention-days: 1

      - name: Upload coverage artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage-report-typescript
          path: ui/coverage/cobertura-coverage.xml
