name: UI Build & Test
on:
  workflow_call:
    inputs:
      build:
        description: 'Whether to build the UI'
        required: false
        default: false
        type: boolean

permissions: read-all

jobs:
  ui:
    runs-on: ubuntu-latest
    name: "UI Test and Build"
    permissions:
      actions: read
      packages: read  
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with: 
          fetch-depth: 0
      
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: ".nvmrc"
          cache: yarn
          cache-dependency-path: "ui/yarn.lock"
      
      - name: Install packages
        run: yarn install --immutable
        working-directory: ui
      
      - name: Lint ui files
        run: yarn lint:github
        working-directory: ui
      
      - name: Run ui tests
        run: yarn test
        working-directory: ui
      
      - name: Build ui
        if: inputs.build
        run: yarn build
        working-directory: ui
      
      - name: Upload UI build artifacts
        if: inputs.build
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: ui-build
          path: ui/build/
          retention-days: 1